### ISSUE TITLE
Analytics run Error: Cannot find module '/app/dist/main.js'

### ISSUE THREAD

**Issue by bartolomej** [bartolomej/moonland#11]
When doing a clean docker productionbuild (after removing images and volumes) I receive the following analytics start error:

```
analytics-prod | internal/modules/cjs/loader.js:905
analytics-prod |   throw err;
analytics-prod |   ^
analytics-prod | 
analytics-prod | Error: Cannot find module '/app/dist/main.js'
analytics-prod |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
analytics-prod |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
analytics-prod |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
analytics-prod |     at internal/main/run_main_module.js:17:47 {
analytics-prod |   code: 'MODULE_NOT_FOUND',
analytics-prod |   requireStack: []
analytics-prod | }
```

**Comment by bartolomej** [comment]
Temporary fix in 6e0d74f3de96d28f433489357858ccab1c75c2ef.
