### ISSUE TITLE
Field 'websiteUrl' doesn't have a default value

### ISSUE THREAD

**Issue by bartolomej** [bartolomej/moonland#12]
Coin aggregation error, because `websiteUrl` is not set:
```
analytics-prod | [Nest] 32  - 01/13/2022, 7:14:29 PM   ERROR [ExceptionsHandler] ER_NO_DEFAULT_FOR_FIELD: Field 'websiteUrl' doesn't have a default value
analytics-prod | QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'websiteUrl' doesn't have a default value
analytics-prod |     at QueryFailedError.TypeORMError [as constructor] (/app/src/error/TypeORMError.ts:7:9)
analytics-prod |     at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
analytics-prod |     at Query.<anonymous> (/app/src/driver/mysql/MysqlQueryRunner.ts:182:37)
analytics-prod |     at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
analytics-prod |     at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
analytics-prod |     at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
analytics-prod |     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
analytics-prod |     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
analytics-prod |     at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
analytics-prod |     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
```

**Comment by bartolomej** [comment]
Fixed in 4f61d8a4d9539c1fe621d0b7c5dd1fdc7c14abb8.
